-- MySQL Script generated by MySQL Workbench
-- Sun 07 May 2017 04:35:54 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ulbora_customer_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ulbora_customer_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ulbora_customer_service` DEFAULT CHARACTER SET utf8 ;
USE `ulbora_customer_service` ;

-- -----------------------------------------------------
-- Table `ulbora_customer_service`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_customer_service`.`address` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `address1` VARCHAR(150) NOT NULL,
  `address2` VARCHAR(150) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `state` VARCHAR(50) NOT NULL,
  `zip` VARCHAR(45) NOT NULL,
  `zip_ext` VARCHAR(45) NULL,
  `country` VARCHAR(150) NOT NULL,
  `customer_email_address` VARCHAR(100) NOT NULL,
  `customer_client_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_address_customer1_idx` (`customer_email_address` ASC, `customer_client_id` ASC),
  CONSTRAINT `fk_address_customer1`
    FOREIGN KEY (`customer_email_address` , `customer_client_id`)
    REFERENCES `ulbora_customer_service`.`customer` (`email_address` , `client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulbora_customer_service`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_customer_service`.`customer` (
  `email_address` VARCHAR(100) NOT NULL,
  `client_id` BIGINT NOT NULL,
  `first_name` VARCHAR(150) NULL,
  `last_name` VARCHAR(150) NULL,
  `company` VARCHAR(150) NULL,
  `primary_phone` VARCHAR(45) NOT NULL,
  `second_phone` VARCHAR(45) NULL,
  `billling_address_id` BIGINT NULL,
  `shipping_address_id` BIGINT NULL,
  `mailing_address_id` BIGINT NULL,
  `date_entered` DATE NOT NULL,
  `date_modified` DATE NULL,
  PRIMARY KEY (`email_address`, `client_id`),
  INDEX `fk_customer_address1_idx` (`billling_address_id` ASC),
  INDEX `fk_customer_address2_idx` (`shipping_address_id` ASC),
  INDEX `fk_customer_address3_idx` (`mailing_address_id` ASC),
  CONSTRAINT `fk_customer_address1`
    FOREIGN KEY (`billling_address_id`)
    REFERENCES `ulbora_customer_service`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_address2`
    FOREIGN KEY (`shipping_address_id`)
    REFERENCES `ulbora_customer_service`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_address3`
    FOREIGN KEY (`mailing_address_id`)
    REFERENCES `ulbora_customer_service`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
